language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

#Travis CI server home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r aws1-sp2-webservice *
  - mkdir -p deploy
  - mv aws1-sp2-webservice.zip deploy/aws1-sp2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정값
    secret_access_key: $AWS_SECRET_KEY #Travis repo settings에 설정값
    bucket: aws1-sp2-build #S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근을 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jjkil@naver.com